---
dataset:
 train:
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_0.h5
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_1.h5
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_2.h5
 validation:
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_3.h5
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_4.h5
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_5.h5
 test:
  - /eos/project/d/dshep/CEVA-hdf5/mix/SSD_6.h5

dataset_misc:
 src_folder: /eos/project/d/dshep/CEVA-hdf5
 size:
  - 30000
  - 12000
  - 90000

output:
 model: ./models
 plots: ./plots

training_pref:
 batch_size_train: 25
 batch_size_validation: 150
 max_epochs: 100
 momentum: .9
 patience: 50
 weight_decay: 0.0005
 workers: 0

evaluation_pref:
 batch_size: 100
 names_classes:
  - 't'
  - 'V'
  - 'H'
 workers: 0

inference_pref:
  samples: 300

ssd_settings:
 confidence_threshold: .01
 feature_maps:
  - phi: 23 
    eta: 22
  - phi: 12 
    eta: 11
 input_dimensions:
  - 3
  - 340
  - 360
 n_classes: 3
 nms: .25
 object_size: 46.
 max_distance: .1
 overlap_threshold: .5
 steps:
  - phi: 16
    eta: 16
  - phi: 34
    eta: 34
 top_k: 100
